#【選擇插件運作語言】
#目前僅支援：
#zh_TW: 繁體中文
#zh_CN: 簡體中文
language: "zh_TW"
#【使用自己修改過的語系檔案】
useModifiedLanguage: false

#【玩家資料儲存類型】
# 使用資料庫，請將此處調整為"sql"或"mongodb"。
# 若不使用則可設為"yml"。
saveType: "yml"

#【資料庫設定】
# 請填入正確的連線資料以便插件連接資料庫。
databaseAddress: "localhost"
databasePort: 3306
databaseName: "sample"
databaseUser: "root"
databasePassword: "1234"

#【插件前綴】
# 使用聲明：
# 更改插件前綴是為各位服主在訊息辨別上更加方便，
# 但更改此前綴並不代表你可以聲明MQ為你的自製插件，
# MQ一直以來的精神為不收費與開源，作者開放此設定也是經過良久考慮，
# 請大家對插件有基本的尊重，感謝配合。
pluginPrefix: "&6MangoQuest>"

#【除錯模式】
# 等級 0 - 不顯示任何除錯訊息
# 等級 1 - 顯示資訊性除錯訊息(ex. 未連接至某些選擇性安裝插件)
# 等級 2 - 顯示玩家小部分行動訊息(ex. 讀取玩家配置、新玩家註冊等)
# 等級 3 - 顯示玩家某些部分行動訊息(ex. 玩家接取任務、放棄任務時顯示訊息)
# 等級 4 - 顯示玩家所有部分行動訊息(ex. 顯示所有玩家任務進度)
# 等級 5 - 災難。(作者專用)
debugLevel: 0

#【每隔X秒儲存玩家資料】
#系統會每隔X秒就儲存一次玩家資料，以免玩家資料流失。
saveIntervalInSeconds: 600


#【是否右鍵NPC開啟對話選單】
#關掉就只能使用指令來接任務。
useRightClickMenu: true

#【玩家最大任務數量】
maxQuestAmount: 4

#【登入時傳送讀取完成訊息】
popLoginMessage: true

#【是否啟用記分板系統】
enableScoreboard: true

#【記分板上可接受的任務之顯示數量】
scoreboardMaxCanTakeQuestAmount: 3

#【使用NPC效果】
useParticleEffect: true

#【使用較寬鬆的物品判定】
# 開啟後，系統將只檢查物品的「名稱」以及「lore」作為判斷依據(色碼仍須完全一致)
useWeakItemCheck: false

#【開放玩家跳過劇情】
enableSkip: false